### ISSUE TITLE
Make fails to compile scalce

### ISSUE THREAD

**Issue by cganote** [sfu-compbio/scalce#1]
Hi,
I'm having some issues getting this to work. It looks like my compiler (gcc 4.9.2) chokes on buffio. Please advise:
`scalce-2.8 $ make
ld -r -b binary -o HELP.o HELP
ld -r -b binary -o patterns.o patterns.bin
g++ -c -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DSCALCE_VERSION=\"2.8\" -O3 -DNDEBUG const.cpp -o const.o
g++ -c -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DSCALCE_VERSION=\"2.8\" -O3 -DNDEBUG buffio.cpp -o buffio.o
buffio.cpp: In function ‘int64_t Zopen(const char_, int, char_)’:
buffio.cpp:52:30: error: ‘gzopen64’ was not declared in this scope
   handle = gzopen64 (bf, "wb");

buffio.cpp:56:32: error: ‘gzopen64’ was not declared in this scope
   handle = gzopen64 (path, "rb");

buffio.cpp: In function ‘int Zclose(void_)’:
buffio.cpp:62:70: error: ‘gzFile_s’ was not declared in this scope
 int     Zclose (void_ handle)                      { return gzclose((gzFile_s*)handle); }

buffio.cpp:62:79: error: expected primary-expression before ‘)’ token
 int     Zclose (void\* handle)                      { return gzclose((gzFile_s*)handle); }

buffio.cpp: In function ‘int64_t Zwrite(void_, void_, int64_t)’:
buffio.cpp:63:70: error: ‘gzFile_s’ was not declared in this scope
 int64_t Zwrite (void\* handle, void _c, int64_t sz) { return gzwrite((gzFile_s_)handle, c, sz); }

buffio.cpp:63:79: error: expected primary-expression before ‘)’ token
 int64_t Zwrite (void\* handle, void _c, int64_t sz) { return gzwrite((gzFile_s_)handle, c, sz); }

buffio.cpp: In function ‘int64_t Zread(void_, void_, int64_t)’:
buffio.cpp:64:69: error: ‘gzFile_s’ was not declared in this scope
 int64_t Zread  (void\* handle, void _c, int64_t sz) { return gzread((gzFile_s_)handle, c, sz); }

buffio.cpp:64:78: error: expected primary-expression before ‘)’ token
 int64_t Zread  (void\* handle, void _c, int64_t sz) { return gzread((gzFile_s_)handle, c, sz); }

buffio.cpp: In function ‘int64_t Zseek(void_, int64_t)’:
buffio.cpp:65:71: error: ‘gzFile_s’ was not declared in this scope
 int64_t Zseek  (void_ handle, int64_t l)           { return gzseek64((gzFile_s*)handle, l, SEEK_SET); }

buffio.cpp:65:80: error: expected primary-expression before ‘)’ token
 int64_t Zseek  (void\* handle, int64_t l)           { return gzseek64((gzFile_s*)handle, l, SEEK_SET); }

buffio.cpp:65:100: error: ‘gzseek64’ was not declared in this scope
 int64_t Zseek  (void\* handle, int64_t l)           { return gzseek64((gzFile_s*)handle, l, SEEK_SET); }

buffio.cpp: In function ‘char\* Zgets(void_, char_, int64_t)’:
buffio.cpp:66:69: error: ‘gzFile_s’ was not declared in this scope
 char   _Zgets  (void_ handle, char _c, int64_t l)  { return gzgets((gzFile_s_)handle, c, l); }

buffio.cpp:66:78: error: expected primary-expression before ‘)’ token
 char   _Zgets  (void_ handle, char _c, int64_t l)  { return gzgets((gzFile_s_)handle, c, l); }

make: **\* [buffio.o] Error 1
`
-Carrie

**Comment by inumanag** [comment]
Hello Carrie,

I just updated the Makefile, which should be able to fetch all the dependencies automatically.

Please try:

```
make download
make
```

Best,
Ibrahim
