### ISSUE TITLE
make download no longer works since one of the used URLs is dead

### ISSUE THREAD

**Issue by rick-heig** [sfu-compbio/scalce#2]
The make download command no longer works since the
http://zlib.net/zlib-1.2.10.tar.gz URL is dead (reports a 404 error)

I managed to build the project by changing the link in the makefile.
Line 48 : I used this link and now the download target of the makefile works again.
curl -L http://www.zlib.net/fossils/zlib-$(ZLIB_VER).tar.gz | tar zxvf -   

You may want to fix the link in the makefile.
Best Regards !
Rick

**Comment by inumanag** [comment]
Sorry for late reply, my notifications haven't been working for some reason.

This should be now fixed. Thanks for reporting it!
