### ISSUE TITLE
make download no longer works since one of the used URLs is dead again！

### ISSUE THREAD

**Issue by Yoniming** [sfu-compbio/scalce#4]
Can you give a new URLs that makes it work great？
curl -L http://www.bzip.org/$(BZIP_VER)/bzip2-$(BZIP_VER).tar.gz | tar zxvf -
curl -L http://zlib.net/zlib-$(ZLIB_VER).tar.gz | tar zxvf -

**Comment by inumanag** [comment]
Fixed--- thanks!
