### ISSUE TITLE
Crash while compressing small data

### ISSUE THREAD

**Issue by KirillKryukov** [sfu-compbio/scalce#8]
Compressing even small data fails with "Segmentation fault" crash.

Example test data: [http://kirill.med.u-tokai.ac.jp/data/temp/scalce-repro-1.fq.gz](http://kirill.med.u-tokai.ac.jp/data/temp/scalce-repro-1.fq.gz). (Test data is first 25 reads of SRR554369_1 dataset, 5.5 kB).

Full repro steps:
```
cd /tmp
mkdir scalce-repro-1
cd scalce-repro-1
git clone https://github.com/sfu-compbio/scalce.git
cd scalce
make download
make
cd ..
wget http://kirill.med.u-tokai.ac.jp/data/temp/scalce-repro-1.fq.gz
gzip -dc scalce-repro-1.fq.gz >a.fq
./scalce/scalce a.fq -o result
```

Output of the last command:
```
SCALCE 2.8 [pthreads; available cores=5]
Buffer size: 131072K, bucket storage size: 4194304K
Segmentation fault (core dumped)
```

Machine: Ubuntu 18.04.1 LTS, GCC 7.4.0, 128 GB RAM. Compressors installed and in PATH: gzip 1.6, bzip 1.0.6, pigz 2.4.

Am I doing something wrong? Let me know if you need any other details or tests.

**Comment by ekimb** [comment]
Same issue here!

**Comment by baraaorabi** [comment]
I'm also having the same issue!

**Comment by inumanag** [comment]
Fixed!
